### ISSUE TITLE
ResponseType as default / code throws error

### ISSUE THREAD

**Issue by Midassi** [microsoft/aad_b2c_webview#32]
Hallo everybody,
trying to Login with `ADB2CEmbedWebView`  using `responseType: Constants.default or authCode (which is the same) `   throws Dio exception.
responseType: idToken or accessToken works fine.

It comes to my understanding that the authCode is used to implement the UserFlow login and call and extract both idToken and refreshToken.

Thanks in advance and best regards.

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
E/flutter (11937): The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
E/flutter (11937): Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
E/flutter (11937): In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
E/flutter (11937): 
E/flutter (11937): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507:7)
E/flutter (11937): #1      _FutureListener.handleError (dart:async/future_impl.dart:180:22)
E/flutter (11937): #2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858:47)
E/flutter (11937): #3      Future._propagateToListeners (dart:async/future_impl.dart:879:13)
E/flutter (11937): #4      Future._completeError (dart:async/future_impl.dart:655:5)
E/flutter (11937): #5      _SyncCompleter._completeError (dart:async/future_impl.dart:63:12)
E/flutter (11937): #6      _Completer.completeError (dart:async/future_impl.dart:27:5)
E/flutter (11937): #7      Future.any.onError (dart:async/future.dart:618:45)
E/flutter (11937): #8      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (11937): #9      _FutureListener.handleError (dart:async/future_impl.dart:177:22)
E/flutter (11937): #10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858:47)
E/flutter (11937): #11     Future._propagateToListeners (dart:async/future_impl.dart:879:13)
E/flutter (11937): #12     Future._completeError (dart:async/future_impl.dart:655:5)
E/flutter (11937): #13     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:745:7)
E/flutter (11937): #14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (11937): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (11937): `

**Comment by Midassi** [comment]
In the Flow in Azure id and accessToken should not be selected. than should work.
